-- DAILY STANDUP LOG
-- Jalankan dalam SQL Editor Supabase

-- 1. Cipta table standup_logs
CREATE TABLE IF NOT EXISTS standup_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  date date not null default current_date,
  today_plan text not null,
  yesterday_status text,
  project_id bigint references projects(id) on delete set null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  UNIQUE(user_id, date)
);

-- 2. Enable RLS
ALTER TABLE standup_logs ENABLE ROW LEVEL SECURITY;

-- 3. Policies
-- Semua staff boleh tengok standup semua orang (transparency)
CREATE POLICY "Anyone can view standups" ON standup_logs FOR SELECT USING (true);

-- Staff boleh submit standup sendiri
CREATE POLICY "Staff can insert own standup" ON standup_logs FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Staff boleh update standup sendiri (kalau nak edit)
CREATE POLICY "Staff can update own standup" ON standup_logs FOR UPDATE USING (auth.uid() = user_id);

-- 4. Kalau table dah ada, tambah column project_id sahaja
ALTER TABLE standup_logs ADD COLUMN IF NOT EXISTS project_id bigint references projects(id) on delete set null;

-- 5. Refresh schema
NOTIFY pgrst, 'reload config';
