-- Copy dan Paste kod ini ke dalam "SQL Editor" di Dashboard Supabase anda

-- 1. Cipta table baru untuk Isu & Cadangan (Standalone)
CREATE TABLE IF NOT EXISTS project_notes (
  id bigint generated by default as identity primary key,
  project_id bigint references projects(id) on delete cascade not null,
  type text check (type in ('issue', 'suggestion')) not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS (Optional but good practice)
ALTER TABLE project_notes ENABLE ROW LEVEL SECURITY;

-- 3. Policy untuk benarkan semua akses (untuk development mudah)
CREATE POLICY "Allow all access to project_notes" ON project_notes FOR ALL USING (true) WITH CHECK (true);

-- 4. Refresh Schema Cache
NOTIFY pgrst, 'reload config';
