-- Copy dan Paste kod ini ke dalam "SQL Editor" di Dashboard Supabase anda

-- 1. Cipta table working_requests
CREATE TABLE IF NOT EXISTS working_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  type text check (type in ('WFH', 'Remote', 'Lapangan')) not null,
  start_date date not null,
  end_date date not null,
  reason text not null,
  status text check (status in ('pending', 'approved', 'rejected')) default 'pending' not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Enable RLS
ALTER TABLE working_requests ENABLE ROW LEVEL SECURITY;

-- 3. Policies
-- Staff boleh lila semua rekod (atau rekod sendiri sahaja - di bawah adalah untuk semua rekod mengikut keperluan app sekarang)
CREATE POLICY "Allow all to view working_requests" ON working_requests FOR SELECT USING (true);

-- Staff boleh hantar permohonan (insert)
CREATE POLICY "Allow staff to insert their own requests" ON working_requests FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Admin boleh kemaskini status (update)
CREATE POLICY "Allow admin to update status" ON working_requests FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE profiles.id = auth.uid() 
    AND (profiles.role = 'admin' OR profiles.role = 'Admin')
  )
);

-- 4. Refresh Schema
NOTIFY pgrst, 'reload config';
